version: '3'

services:
  bot:
    build: .
    volumes:
      - type: bind
        source: ./data/guilds.json
        target: /home/app/data/guilds.json
    restart: unless-stopped
    env_file:
      - .env
